export const ATTR_DEPLOYMENT_ENVIRONMENT = 'deployment.environment.name'
export const ATTR_SERVICE_INSTANCE_ID = 'service.instance.id'
export const ATTR_SERVICE_NAME = 'service.name'
export const ATTR_SERVICE_NAMESPACE = 'service.namespace'
export const ATTR_SERVICE_VERSION = 'service.version'
