
export default {
  tags: [
    'Backend',
    'Frontend',
    'Code Review',
    'System Design',
    'UX/UI/Design',
    'iOS',
    'Android',
    'QA',
    'Marketing',
    'Content/Copy',
    'Databases',
    'Data Science/ML',
    'Аналитика',
    'Network',
    'Cloud',
    'DevOps/SRE',
    'Agile',
    'Team Lead/Management',
    'Project Management',
    'Product Management',
    'Entrepreneurship',
    'DevRel',
    'HR',
    'Карьера',
    'Собеседования',
    'Другое',
  ],
  price: [
    '✅ Бесплатно',
    '1000 руб',
    '2000 руб',
    '3000 руб',
    '4000 руб',
    '5000 руб',
    '6000 руб',
    '7000 руб',
    '8000 руб',
    '9000 руб',
    '🤝 По договоренности',
  ],
  experience: [
    '<2 лет',
    '😎 2-5 лет',
    '😎 5-10 лет',
    '🌟 10+ лет',
  ],
  sponsors: [
    'Эксперт Авито',
    'Сообщество Онтико',
  ],
}
