export default {
  tags: [
    'Backend',
    'Frontend',
    'Code Review',
    'System Design',
    'UX/UI/Design',
    'iOS',
    'Android',
    'QA',
    'Marketing',
    'Content/Copy',
    'Databases',
    'Data Science/ML',
    'Аналитика',
    'Сети',
    'Cloud',
    'DevOps/SRE',
    'Agile',
    'Team Lead/Management',
    'Project Management',
    'Product Management',
    'Entrepreneurship',
    'DevRel',
    'HR',
    'Карьера',
    'Собеседования',
    'Другое',
  ],
  t: {
    development: ['Backend', 'Frontend', 'iOS', 'Android', 'System Design', 'Code Review'],
    design: ['UX/UI/Design'],
    ops: ['DevOps/SRE', 'Databases', 'Сети', 'Cloud'],
    hr: ['HR', 'Карьера', 'Собеседования', 'Entrepreneurship', 'DevRel'],
    management: ['Agile', 'Team Lead/Management', 'Project Management', 'Product Management'],
    qa: ['QA'],
    marketing: ['Marketing', 'Content/Copy'],
    analytics: ['Аналитика'],
    ds: ['Data Science/ML'],
    rest: ['Data Science/ML', 'UX/UI/Design', 'QA', 'Аналитика', 'Другое'],
  },
  price: [
    'Бесплатно',
    '1000 руб',
    '2000 руб',
    '3000 руб',
    '4000 руб',
    '5000 руб',
    '6000 руб',
    '7000 руб',
    '8000 руб',
    '9000 руб',
    'По договоренности',
  ],
  experience: [
    // { label: '<2 лет', airtableKey: '0-2' },
    { label: '2-5 лет', airtableKey: '2-5' },
    { label: '5-10 лет', airtableKey: '5-10' },
    { label: '10+ лет', airtableKey: '10+' },
  ],
  sponsors: ['Эксперт Авито', 'Сообщество Онтико', 'Наставник Яндекс.Практикума'],
}
