export default {
  tags: [
    'Backend',
    'Frontend',
    'Code Review',
    'System Design',
    'UX/UI/Design',
    'iOS',
    'Android',
    'QA',
    'Marketing',
    'Content/Copy',
    'Databases',
    'Data Science/ML',
    'Аналитика',
    'Сети',
    'Cloud',
    'DevOps/SRE',
    'Agile',
    'Team Lead/Management',
    'Project Management',
    'Product Management',
    'Entrepreneurship',
    'DevRel',
    'HR',
    'Карьера',
    'Собеседования',
    'Другое',
  ],
  byTags: {
    development: ['Backend', 'Frontend', 'iOS', 'Android', 'System Design', 'Code Review'],
    management: ['Agile', 'Team Lead/Management', 'Project Management', 'Product Management'],
    ops: ['DevOps/SRE', 'Databases', 'Сети', 'Cloud'],
    hr: ['HR', 'Карьера', 'Собеседования', 'Entrepreneurship', 'DevRel'],
    marketing: ['Marketing', 'Content/Copy'],
    rest: ['Data Science/ML', 'UX/UI/Design', 'QA', 'Аналитика', 'Другое'],
  },
  price: [
    'Бесплатно',
    '1000 руб',
    '2000 руб',
    '3000 руб',
    '4000 руб',
    '5000 руб',
    '6000 руб',
    '7000 руб',
    '8000 руб',
    '9000 руб',
    '10000 руб',
    'По договоренности',
  ],
  experience: {
    '2-5 лет': '2-5',
    '5-10 лет': '5-10',
    '10+ лет': '10+',
  },
  byPrice: {
    Бесплатно: ['Бесплатно'],
    'До 1 000 руб.': ['Бесплатно', '1000 руб'],
    'До 3 000 руб.': ['Бесплатно', '1000 руб', '2000 руб', '3000 руб'],
    'До 5 000 руб.': ['Бесплатно', '1000 руб', '2000 руб', '3000 руб', '4000 руб', '5000 руб'],
    'До 7 000 руб.': [
      'Бесплатно',
      '1000 руб',
      '2000 руб',
      '3000 руб',
      '4000 руб',
      '5000 руб',
      '6000 руб',
      '7000 руб',
    ],
    'До 10 000 руб.': [
      'Бесплатно',
      '1000 руб',
      '2000 руб',
      '3000 руб',
      '4000 руб',
      '5000 руб',
      '6000 руб',
      '7000 руб',
      '8000 руб',
      '9000 руб',
    ],
    'По договоренности': ['По договоренности'],
  },
  sponsors: ['Эксперт Авито', 'Сообщество Онтико'],
}
