apiVersion: v1
kind: Secret
metadata:
  name: getmentor-secrets
  namespace: getmentor
  labels:
    app: getmentor
type: Opaque
data:
  # These are placeholder values that should be replaced with actual base64-encoded secrets
  # In a real deployment, these would be injected by the CI/CD pipeline
  AIRTABLE_API_KEY: "UExBQ0VIT0xERVJfVkFMVUU="  # base64 encoded "PLACEHOLDER_VALUE"
  AIRTABLE_BASE_ID: "UExBQ0VIT0xERVJfVkFMVUU="  # base64 encoded "PLACEHOLDER_VALUE"
  APPLICATIONINSIGHTS_CONNECTION_STRING: "UExBQ0VIT0xERVJfVkFMVUU="  # base64 encoded "PLACEHOLDER_VALUE"
  PYROSCOPE_SERVER_ADDRESS: "UExBQ0VIT0xERVJfVkFMVUU="  # base64 encoded "PLACEHOLDER_VALUE"
  PYRSOCOPE_USER_ID: "UExBQ0VIT0xERVJfVkFMVUU="  # base64 encoded "PLACEHOLDER_VALUE"
  PYRSOCOPE_PASSWORD: "UExBQ0VIT0xERVJfVkFMVUU="  # base64 encoded "PLACEHOLDER_VALUE"