name: Deploy to DigitalOcean Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DIGITALOCEAN_REGISTRY: ${{ secrets.DIGITALOCEAN_REGISTRY }}
  DIGITALOCEAN_CLUSTER_NAME: ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/${{ env.DIGITALOCEAN_REGISTRY }}/getmentor:${{ env.IMAGE_TAG }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ env.DIGITALOCEAN_CLUSTER_NAME }}

      - name: Create ConfigMap
        run: |
          kubectl create configmap getmentor-config \
            --namespace=getmentor \
            --from-literal=INDEX_PAGE_REVALIDATION_INTERVAL_IN_SECONDS=${{ secrets.INDEX_PAGE_REVALIDATION_INTERVAL_IN_SECONDS }} \
            --from-literal=AZURE_STORAGE_DOMAIN=${{ secrets.AZURE_STORAGE_DOMAIN }} \
            --from-literal=BUILD_ON_GITHUB=${{ secrets.BUILD_ON_GITHUB }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create Secret
        run: |
          kubectl create secret generic getmentor-secrets \
            --namespace=getmentor \
            --from-literal=AIRTABLE_API_KEY=${{ secrets.AIRTABLE_API_KEY }} \
            --from-literal=AIRTABLE_BASE_ID=${{ secrets.AIRTABLE_BASE_ID }} \
            --from-literal=APPLICATIONINSIGHTS_CONNECTION_STRING=${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }} \
            --from-literal=PYROSCOPE_SERVER_ADDRESS=${{ secrets.PYROSCOPE_SERVER_ADDRESS }} \
            --from-literal=PYRSOCOPE_USER_ID=${{ secrets.PYRSOCOPE_USER_ID }} \
            --from-literal=PYRSOCOPE_PASSWORD=${{ secrets.PYRSOCOPE_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          cd k8s/digitalocean
          export DIGITALOCEAN_REGISTRY=${{ env.DIGITALOCEAN_REGISTRY }}
          export IMAGE_TAG=${{ env.IMAGE_TAG }}
          kubectl apply -k . --namespace=getmentor

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/getmentor -n getmentor
